"""Grade HTML extraction quality for all .eml files in eml_examples/.

For each .eml file:
  1. Loads the email via load_eml()
  2. Runs EmailParser.parse() to extract plain_text, links, and images
  3. Sends a grading prompt to Claude asking for Completeness / Cleanliness /
     Link quality scores (1-10 each) plus specific observations
  4. Writes a summary report to eml_examples/extraction_report.md

Usage:
    python scripts/grade_extraction.py

Requires ANTHROPIC_API_KEY in .env or environment.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Ensure project root is on the path when running as a script
sys.path.insert(0, str(Path(__file__).parent.parent))

import anthropic
from dotenv import load_dotenv

from agent.parsers.email_parser import EmailParser
from agent.utils.eml_loader import load_eml

load_dotenv()

_GRADE_PROMPT = """\
You are evaluating the quality of an HTML email parser's output. Below is:
1. The email sender and subject
2. The extracted plain text (after boilerplate removal)
3. The extracted article links (title + URL)
4. The extracted image URLs

Please grade on three dimensions (score 1–10 each):
- **Completeness** (10 = all meaningful content preserved, no important sections missing)
- **Cleanliness** (10 = no boilerplate, tracking text, or navigation noise remaining)
- **Link quality** (10 = only real article links, no unsubscribe/social/tracking links)

For each dimension, briefly explain your score and cite specific examples from the output.
Finally, suggest 1–2 concrete parser improvements if scores are below 8.

---
**Sender:** {sender}
**Subject:** {subject}

**Extracted plain text ({plain_len} chars):**
```
{plain_text}
```

**Extracted links ({link_count}):**
{links_block}

**Extracted images ({image_count}):**
{images_block}
---
"""


def _format_links(links) -> str:
    if not links:
        return "(none)"
    return "\n".join(f"- [{lnk.title}]({lnk.url})" for lnk in links)


def _format_images(images) -> str:
    if not images:
        return "(none)"
    return "\n".join(f"- {img}" for img in images)


def main() -> None:
    eml_dir = Path("eml_examples")
    if not eml_dir.exists():
        print("No eml_examples/ directory found. Add .eml files there first.", file=sys.stderr)
        sys.exit(1)

    eml_files = sorted(eml_dir.glob("*.eml"))
    if not eml_files:
        print("No .eml files found in eml_examples/.", file=sys.stderr)
        sys.exit(1)

    import os
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("ANTHROPIC_API_KEY not set.", file=sys.stderr)
        sys.exit(1)

    client = anthropic.Anthropic(api_key=api_key)
    parser = EmailParser()

    report_lines: list[str] = [
        "# Extraction Quality Report\n",
        f"Generated by `scripts/grade_extraction.py` — {len(eml_files)} emails graded.\n",
        "---\n",
    ]

    for eml_path in eml_files:
        print(f"Grading: {eml_path.name} …", flush=True)
        email = load_eml(eml_path)
        parsed = parser.parse(email)

        plain_preview = (parsed.plain_text or "")[:3000]
        prompt = _GRADE_PROMPT.format(
            sender=email.sender,
            subject=email.subject,
            plain_len=len(parsed.plain_text or ""),
            plain_text=plain_preview,
            link_count=len(parsed.links),
            links_block=_format_links(parsed.links),
            image_count=len(parsed.images),
            images_block=_format_images(parsed.images),
        )

        response = client.messages.create(
            model="claude-sonnet-4-6",
            max_tokens=1024,
            messages=[{"role": "user", "content": prompt}],
        )
        grade_text = response.content[0].text.strip()

        report_lines += [
            f"## {eml_path.stem}\n",
            f"**Sender:** {email.sender}  \n**Subject:** {email.subject}\n",
            f"**Stats:** {len(parsed.plain_text or '')} chars plain text · "
            f"{len(parsed.links)} links · {len(parsed.images)} images\n",
            "\n### Claude's Assessment\n",
            grade_text,
            "\n\n---\n",
        ]

    report_path = eml_dir / "extraction_report.md"
    report_path.write_text("\n".join(report_lines))
    print(f"\nReport written to {report_path}")


if __name__ == "__main__":
    main()
